# Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

require 'minitest/autorun'
require 'base64'
require 'json'
require 'openssl'
require 'zlib'
require_relative '../lib/getstream_ruby/generated/webhook'

class WebhookTest < Minitest::Test
  SECRET = 'test-webhook-secret'
  BODY = '{"type":"test.event"}'

  def compute_signature(body, secret)
    OpenSSL::HMAC.hexdigest('SHA256', secret, body)
  end

  def test_verify_signature_valid
    signature = compute_signature(BODY, SECRET)
    assert StreamChat::Webhook.verify_signature(BODY, signature, SECRET)
  end

  def test_verify_signature_wrong_signature
    refute StreamChat::Webhook.verify_signature(BODY, 'invalidsignature', SECRET)
  end

  def test_verify_signature_tampered_body
    signature = compute_signature(BODY, SECRET)
    refute StreamChat::Webhook.verify_signature('{"type":"tampered"}', signature, SECRET)
  end

  def test_verify_signature_wrong_secret
    signature = compute_signature(BODY, SECRET)
    refute StreamChat::Webhook.verify_signature(BODY, signature, 'wrong-secret')
  end

  def test_verify_signature_empty_signature
    refute StreamChat::Webhook.verify_signature(BODY, '', SECRET)
  end

  def test_get_event_type_from_string
    assert_equal 'message.new', StreamChat::Webhook.get_event_type('{"type":"message.new"}')
  end

  def test_get_event_type_from_hash
    assert_equal 'message.new', StreamChat::Webhook.get_event_type({ 'type' => 'message.new' })
  end

  def test_get_event_type_missing_field
    assert_nil StreamChat::Webhook.get_event_type('{"foo":"bar"}')
  end

  def test_get_event_type_empty_object
    assert_nil StreamChat::Webhook.get_event_type('{}')
  end
  def test_parse_
    event = StreamChat::Webhook.parse_webhook_event('{"type":"*"}')
    assert_equal 'StreamChat::CustomEvent', event.class.name
  end

  def test_parse_appeal_accepted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"appeal.accepted"}')
    assert_equal 'StreamChat::AppealAcceptedEvent', event.class.name
  end

  def test_parse_appeal_created
    event = StreamChat::Webhook.parse_webhook_event('{"type":"appeal.created"}')
    assert_equal 'StreamChat::AppealCreatedEvent', event.class.name
  end

  def test_parse_appeal_rejected
    event = StreamChat::Webhook.parse_webhook_event('{"type":"appeal.rejected"}')
    assert_equal 'StreamChat::AppealRejectedEvent', event.class.name
  end

  def test_parse_call_accepted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.accepted"}')
    assert_equal 'StreamChat::CallAcceptedEvent', event.class.name
  end

  def test_parse_call_blocked_user
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.blocked_user"}')
    assert_equal 'StreamChat::BlockedUserEvent', event.class.name
  end

  def test_parse_call_closed_caption
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.closed_caption"}')
    assert_equal 'StreamChat::ClosedCaptionEvent', event.class.name
  end

  def test_parse_call_closed_captions_failed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.closed_captions_failed"}')
    assert_equal 'StreamChat::CallClosedCaptionsFailedEvent', event.class.name
  end

  def test_parse_call_closed_captions_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.closed_captions_started"}')
    assert_equal 'StreamChat::CallClosedCaptionsStartedEvent', event.class.name
  end

  def test_parse_call_closed_captions_stopped
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.closed_captions_stopped"}')
    assert_equal 'StreamChat::CallClosedCaptionsStoppedEvent', event.class.name
  end

  def test_parse_call_created
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.created"}')
    assert_equal 'StreamChat::CallCreatedEvent', event.class.name
  end

  def test_parse_call_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.deleted"}')
    assert_equal 'StreamChat::CallDeletedEvent', event.class.name
  end

  def test_parse_call_dtmf
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.dtmf"}')
    assert_equal 'StreamChat::CallDTMFEvent', event.class.name
  end

  def test_parse_call_ended
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.ended"}')
    assert_equal 'StreamChat::CallEndedEvent', event.class.name
  end

  def test_parse_call_frame_recording_failed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.frame_recording_failed"}')
    assert_equal 'StreamChat::CallFrameRecordingFailedEvent', event.class.name
  end

  def test_parse_call_frame_recording_ready
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.frame_recording_ready"}')
    assert_equal 'StreamChat::CallFrameRecordingFrameReadyEvent', event.class.name
  end

  def test_parse_call_frame_recording_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.frame_recording_started"}')
    assert_equal 'StreamChat::CallFrameRecordingStartedEvent', event.class.name
  end

  def test_parse_call_frame_recording_stopped
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.frame_recording_stopped"}')
    assert_equal 'StreamChat::CallFrameRecordingStoppedEvent', event.class.name
  end

  def test_parse_call_hls_broadcasting_failed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.hls_broadcasting_failed"}')
    assert_equal 'StreamChat::CallHLSBroadcastingFailedEvent', event.class.name
  end

  def test_parse_call_hls_broadcasting_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.hls_broadcasting_started"}')
    assert_equal 'StreamChat::CallHLSBroadcastingStartedEvent', event.class.name
  end

  def test_parse_call_hls_broadcasting_stopped
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.hls_broadcasting_stopped"}')
    assert_equal 'StreamChat::CallHLSBroadcastingStoppedEvent', event.class.name
  end

  def test_parse_call_kicked_user
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.kicked_user"}')
    assert_equal 'StreamChat::KickedUserEvent', event.class.name
  end

  def test_parse_call_live_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.live_started"}')
    assert_equal 'StreamChat::CallLiveStartedEvent', event.class.name
  end

  def test_parse_call_member_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.member_added"}')
    assert_equal 'StreamChat::CallMemberAddedEvent', event.class.name
  end

  def test_parse_call_member_removed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.member_removed"}')
    assert_equal 'StreamChat::CallMemberRemovedEvent', event.class.name
  end

  def test_parse_call_member_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.member_updated"}')
    assert_equal 'StreamChat::CallMemberUpdatedEvent', event.class.name
  end

  def test_parse_call_member_updated_permission
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.member_updated_permission"}')
    assert_equal 'StreamChat::CallMemberUpdatedPermissionEvent', event.class.name
  end

  def test_parse_call_missed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.missed"}')
    assert_equal 'StreamChat::CallMissedEvent', event.class.name
  end

  def test_parse_call_moderation_blur
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.moderation_blur"}')
    assert_equal 'StreamChat::CallModerationBlurEvent', event.class.name
  end

  def test_parse_call_moderation_warning
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.moderation_warning"}')
    assert_equal 'StreamChat::CallModerationWarningEvent', event.class.name
  end

  def test_parse_call_notification
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.notification"}')
    assert_equal 'StreamChat::CallNotificationEvent', event.class.name
  end

  def test_parse_call_permission_request
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.permission_request"}')
    assert_equal 'StreamChat::PermissionRequestEvent', event.class.name
  end

  def test_parse_call_permissions_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.permissions_updated"}')
    assert_equal 'StreamChat::UpdatedCallPermissionsEvent', event.class.name
  end

  def test_parse_call_reaction_new
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.reaction_new"}')
    assert_equal 'StreamChat::CallReactionEvent', event.class.name
  end

  def test_parse_call_recording_failed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.recording_failed"}')
    assert_equal 'StreamChat::CallRecordingFailedEvent', event.class.name
  end

  def test_parse_call_recording_ready
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.recording_ready"}')
    assert_equal 'StreamChat::CallRecordingReadyEvent', event.class.name
  end

  def test_parse_call_recording_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.recording_started"}')
    assert_equal 'StreamChat::CallRecordingStartedEvent', event.class.name
  end

  def test_parse_call_recording_stopped
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.recording_stopped"}')
    assert_equal 'StreamChat::CallRecordingStoppedEvent', event.class.name
  end

  def test_parse_call_rejected
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.rejected"}')
    assert_equal 'StreamChat::CallRejectedEvent', event.class.name
  end

  def test_parse_call_ring
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.ring"}')
    assert_equal 'StreamChat::CallRingEvent', event.class.name
  end

  def test_parse_call_rtmp_broadcast_failed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.rtmp_broadcast_failed"}')
    assert_equal 'StreamChat::CallRtmpBroadcastFailedEvent', event.class.name
  end

  def test_parse_call_rtmp_broadcast_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.rtmp_broadcast_started"}')
    assert_equal 'StreamChat::CallRtmpBroadcastStartedEvent', event.class.name
  end

  def test_parse_call_rtmp_broadcast_stopped
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.rtmp_broadcast_stopped"}')
    assert_equal 'StreamChat::CallRtmpBroadcastStoppedEvent', event.class.name
  end

  def test_parse_call_session_ended
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_ended"}')
    assert_equal 'StreamChat::CallSessionEndedEvent', event.class.name
  end

  def test_parse_call_session_participant_count_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_participant_count_updated"}')
    assert_equal 'StreamChat::CallSessionParticipantCountsUpdatedEvent', event.class.name
  end

  def test_parse_call_session_participant_joined
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_participant_joined"}')
    assert_equal 'StreamChat::CallSessionParticipantJoinedEvent', event.class.name
  end

  def test_parse_call_session_participant_left
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_participant_left"}')
    assert_equal 'StreamChat::CallSessionParticipantLeftEvent', event.class.name
  end

  def test_parse_call_session_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_started"}')
    assert_equal 'StreamChat::CallSessionStartedEvent', event.class.name
  end

  def test_parse_call_stats_report_ready
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.stats_report_ready"}')
    assert_equal 'StreamChat::CallStatsReportReadyEvent', event.class.name
  end

  def test_parse_call_transcription_failed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.transcription_failed"}')
    assert_equal 'StreamChat::CallTranscriptionFailedEvent', event.class.name
  end

  def test_parse_call_transcription_ready
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.transcription_ready"}')
    assert_equal 'StreamChat::CallTranscriptionReadyEvent', event.class.name
  end

  def test_parse_call_transcription_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.transcription_started"}')
    assert_equal 'StreamChat::CallTranscriptionStartedEvent', event.class.name
  end

  def test_parse_call_transcription_stopped
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.transcription_stopped"}')
    assert_equal 'StreamChat::CallTranscriptionStoppedEvent', event.class.name
  end

  def test_parse_call_unblocked_user
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.unblocked_user"}')
    assert_equal 'StreamChat::UnblockedUserEvent', event.class.name
  end

  def test_parse_call_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.updated"}')
    assert_equal 'StreamChat::CallUpdatedEvent', event.class.name
  end

  def test_parse_call_user_feedback_submitted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.user_feedback_submitted"}')
    assert_equal 'StreamChat::CallUserFeedbackSubmittedEvent', event.class.name
  end

  def test_parse_call_user_muted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"call.user_muted"}')
    assert_equal 'StreamChat::CallUserMutedEvent', event.class.name
  end

  def test_parse_campaign_completed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"campaign.completed"}')
    assert_equal 'StreamChat::CampaignCompletedEvent', event.class.name
  end

  def test_parse_campaign_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"campaign.started"}')
    assert_equal 'StreamChat::CampaignStartedEvent', event.class.name
  end

  def test_parse_channel_created
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.created"}')
    assert_equal 'StreamChat::ChannelCreatedEvent', event.class.name
  end

  def test_parse_channel_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.deleted"}')
    assert_equal 'StreamChat::ChannelDeletedEvent', event.class.name
  end

  def test_parse_channel_frozen
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.frozen"}')
    assert_equal 'StreamChat::ChannelFrozenEvent', event.class.name
  end

  def test_parse_channel_hidden
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.hidden"}')
    assert_equal 'StreamChat::ChannelHiddenEvent', event.class.name
  end

  def test_parse_channel_max_streak_changed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.max_streak_changed"}')
    assert_equal 'StreamChat::MaxStreakChangedEvent', event.class.name
  end

  def test_parse_channel_muted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.muted"}')
    assert_equal 'StreamChat::ChannelMutedEvent', event.class.name
  end

  def test_parse_channel_truncated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.truncated"}')
    assert_equal 'StreamChat::ChannelTruncatedEvent', event.class.name
  end

  def test_parse_channel_unfrozen
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.unfrozen"}')
    assert_equal 'StreamChat::ChannelUnFrozenEvent', event.class.name
  end

  def test_parse_channel_unmuted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.unmuted"}')
    assert_equal 'StreamChat::ChannelUnmutedEvent', event.class.name
  end

  def test_parse_channel_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.updated"}')
    assert_equal 'StreamChat::ChannelUpdatedEvent', event.class.name
  end

  def test_parse_channel_visible
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.visible"}')
    assert_equal 'StreamChat::ChannelVisibleEvent', event.class.name
  end

  def test_parse_channel_batch_update_completed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel_batch_update.completed"}')
    assert_equal 'StreamChat::ChannelBatchCompletedEvent', event.class.name
  end

  def test_parse_channel_batch_update_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"channel_batch_update.started"}')
    assert_equal 'StreamChat::ChannelBatchStartedEvent', event.class.name
  end

  def test_parse_custom
    event = StreamChat::Webhook.parse_webhook_event('{"type":"custom"}')
    assert_equal 'StreamChat::CustomVideoEvent', event.class.name
  end

  def test_parse_export_bulk_image_moderation_error
    event = StreamChat::Webhook.parse_webhook_event('{"type":"export.bulk_image_moderation.error"}')
    assert_equal 'StreamChat::AsyncExportErrorEvent', event.class.name
  end

  def test_parse_export_bulk_image_moderation_success
    event = StreamChat::Webhook.parse_webhook_event('{"type":"export.bulk_image_moderation.success"}')
    assert_equal 'StreamChat::AsyncBulkImageModerationEvent', event.class.name
  end

  def test_parse_export_channels_error
    event = StreamChat::Webhook.parse_webhook_event('{"type":"export.channels.error"}')
    assert_equal 'StreamChat::AsyncExportErrorEvent', event.class.name
  end

  def test_parse_export_channels_success
    event = StreamChat::Webhook.parse_webhook_event('{"type":"export.channels.success"}')
    assert_equal 'StreamChat::AsyncExportChannelsEvent', event.class.name
  end

  def test_parse_export_moderation_logs_error
    event = StreamChat::Webhook.parse_webhook_event('{"type":"export.moderation_logs.error"}')
    assert_equal 'StreamChat::AsyncExportErrorEvent', event.class.name
  end

  def test_parse_export_moderation_logs_success
    event = StreamChat::Webhook.parse_webhook_event('{"type":"export.moderation_logs.success"}')
    assert_equal 'StreamChat::AsyncExportModerationLogsEvent', event.class.name
  end

  def test_parse_export_users_error
    event = StreamChat::Webhook.parse_webhook_event('{"type":"export.users.error"}')
    assert_equal 'StreamChat::AsyncExportErrorEvent', event.class.name
  end

  def test_parse_export_users_success
    event = StreamChat::Webhook.parse_webhook_event('{"type":"export.users.success"}')
    assert_equal 'StreamChat::AsyncExportUsersEvent', event.class.name
  end

  def test_parse_feeds_activity_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.added"}')
    assert_equal 'StreamChat::ActivityAddedEvent', event.class.name
  end

  def test_parse_feeds_activity_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.deleted"}')
    assert_equal 'StreamChat::ActivityDeletedEvent', event.class.name
  end

  def test_parse_feeds_activity_feedback
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.feedback"}')
    assert_equal 'StreamChat::ActivityFeedbackEvent', event.class.name
  end

  def test_parse_feeds_activity_marked
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.marked"}')
    assert_equal 'StreamChat::ActivityMarkEvent', event.class.name
  end

  def test_parse_feeds_activity_pinned
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.pinned"}')
    assert_equal 'StreamChat::ActivityPinnedEvent', event.class.name
  end

  def test_parse_feeds_activity_reaction_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.reaction.added"}')
    assert_equal 'StreamChat::ActivityReactionAddedEvent', event.class.name
  end

  def test_parse_feeds_activity_reaction_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.reaction.deleted"}')
    assert_equal 'StreamChat::ActivityReactionDeletedEvent', event.class.name
  end

  def test_parse_feeds_activity_reaction_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.reaction.updated"}')
    assert_equal 'StreamChat::ActivityReactionUpdatedEvent', event.class.name
  end

  def test_parse_feeds_activity_removed_from_feed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.removed_from_feed"}')
    assert_equal 'StreamChat::ActivityRemovedFromFeedEvent', event.class.name
  end

  def test_parse_feeds_activity_restored
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.restored"}')
    assert_equal 'StreamChat::ActivityRestoredEvent', event.class.name
  end

  def test_parse_feeds_activity_unpinned
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.unpinned"}')
    assert_equal 'StreamChat::ActivityUnpinnedEvent', event.class.name
  end

  def test_parse_feeds_activity_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.updated"}')
    assert_equal 'StreamChat::ActivityUpdatedEvent', event.class.name
  end

  def test_parse_feeds_bookmark_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark.added"}')
    assert_equal 'StreamChat::BookmarkAddedEvent', event.class.name
  end

  def test_parse_feeds_bookmark_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark.deleted"}')
    assert_equal 'StreamChat::BookmarkDeletedEvent', event.class.name
  end

  def test_parse_feeds_bookmark_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark.updated"}')
    assert_equal 'StreamChat::BookmarkUpdatedEvent', event.class.name
  end

  def test_parse_feeds_bookmark_folder_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark_folder.deleted"}')
    assert_equal 'StreamChat::BookmarkFolderDeletedEvent', event.class.name
  end

  def test_parse_feeds_bookmark_folder_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark_folder.updated"}')
    assert_equal 'StreamChat::BookmarkFolderUpdatedEvent', event.class.name
  end

  def test_parse_feeds_comment_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.added"}')
    assert_equal 'StreamChat::CommentAddedEvent', event.class.name
  end

  def test_parse_feeds_comment_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.deleted"}')
    assert_equal 'StreamChat::CommentDeletedEvent', event.class.name
  end

  def test_parse_feeds_comment_reaction_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.reaction.added"}')
    assert_equal 'StreamChat::CommentReactionAddedEvent', event.class.name
  end

  def test_parse_feeds_comment_reaction_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.reaction.deleted"}')
    assert_equal 'StreamChat::CommentReactionDeletedEvent', event.class.name
  end

  def test_parse_feeds_comment_reaction_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.reaction.updated"}')
    assert_equal 'StreamChat::CommentReactionUpdatedEvent', event.class.name
  end

  def test_parse_feeds_comment_restored
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.restored"}')
    assert_equal 'StreamChat::CommentRestoredEvent', event.class.name
  end

  def test_parse_feeds_comment_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.updated"}')
    assert_equal 'StreamChat::CommentUpdatedEvent', event.class.name
  end

  def test_parse_feeds_feed_created
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed.created"}')
    assert_equal 'StreamChat::FeedCreatedEvent', event.class.name
  end

  def test_parse_feeds_feed_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed.deleted"}')
    assert_equal 'StreamChat::FeedDeletedEvent', event.class.name
  end

  def test_parse_feeds_feed_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed.updated"}')
    assert_equal 'StreamChat::FeedUpdatedEvent', event.class.name
  end

  def test_parse_feeds_feed_group_changed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_group.changed"}')
    assert_equal 'StreamChat::FeedGroupChangedEvent', event.class.name
  end

  def test_parse_feeds_feed_group_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_group.deleted"}')
    assert_equal 'StreamChat::FeedGroupDeletedEvent', event.class.name
  end

  def test_parse_feeds_feed_group_restored
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_group.restored"}')
    assert_equal 'StreamChat::FeedGroupRestoredEvent', event.class.name
  end

  def test_parse_feeds_feed_member_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_member.added"}')
    assert_equal 'StreamChat::FeedMemberAddedEvent', event.class.name
  end

  def test_parse_feeds_feed_member_removed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_member.removed"}')
    assert_equal 'StreamChat::FeedMemberRemovedEvent', event.class.name
  end

  def test_parse_feeds_feed_member_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_member.updated"}')
    assert_equal 'StreamChat::FeedMemberUpdatedEvent', event.class.name
  end

  def test_parse_feeds_follow_created
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.follow.created"}')
    assert_equal 'StreamChat::FollowCreatedEvent', event.class.name
  end

  def test_parse_feeds_follow_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.follow.deleted"}')
    assert_equal 'StreamChat::FollowDeletedEvent', event.class.name
  end

  def test_parse_feeds_follow_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.follow.updated"}')
    assert_equal 'StreamChat::FollowUpdatedEvent', event.class.name
  end

  def test_parse_feeds_notification_feed_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.notification_feed.updated"}')
    assert_equal 'StreamChat::NotificationFeedUpdatedEvent', event.class.name
  end

  def test_parse_feeds_stories_feed_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.stories_feed.updated"}')
    assert_equal 'StreamChat::StoriesFeedUpdatedEvent', event.class.name
  end

  def test_parse_flag_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"flag.updated"}')
    assert_equal 'StreamChat::FlagUpdatedEvent', event.class.name
  end

  def test_parse_ingress_error
    event = StreamChat::Webhook.parse_webhook_event('{"type":"ingress.error"}')
    assert_equal 'StreamChat::IngressErrorEvent', event.class.name
  end

  def test_parse_ingress_started
    event = StreamChat::Webhook.parse_webhook_event('{"type":"ingress.started"}')
    assert_equal 'StreamChat::IngressStartedEvent', event.class.name
  end

  def test_parse_ingress_stopped
    event = StreamChat::Webhook.parse_webhook_event('{"type":"ingress.stopped"}')
    assert_equal 'StreamChat::IngressStoppedEvent', event.class.name
  end

  def test_parse_member_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"member.added"}')
    assert_equal 'StreamChat::MemberAddedEvent', event.class.name
  end

  def test_parse_member_removed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"member.removed"}')
    assert_equal 'StreamChat::MemberRemovedEvent', event.class.name
  end

  def test_parse_member_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"member.updated"}')
    assert_equal 'StreamChat::MemberUpdatedEvent', event.class.name
  end

  def test_parse_message_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"message.deleted"}')
    assert_equal 'StreamChat::MessageDeletedEvent', event.class.name
  end

  def test_parse_message_flagged
    event = StreamChat::Webhook.parse_webhook_event('{"type":"message.flagged"}')
    assert_equal 'StreamChat::MessageFlaggedEvent', event.class.name
  end

  def test_parse_message_new
    event = StreamChat::Webhook.parse_webhook_event('{"type":"message.new"}')
    assert_equal 'StreamChat::MessageNewEvent', event.class.name
  end

  def test_parse_message_pending
    event = StreamChat::Webhook.parse_webhook_event('{"type":"message.pending"}')
    assert_equal 'StreamChat::PendingMessageEvent', event.class.name
  end

  def test_parse_message_read
    event = StreamChat::Webhook.parse_webhook_event('{"type":"message.read"}')
    assert_equal 'StreamChat::MessageReadEvent', event.class.name
  end

  def test_parse_message_unblocked
    event = StreamChat::Webhook.parse_webhook_event('{"type":"message.unblocked"}')
    assert_equal 'StreamChat::MessageUnblockedEvent', event.class.name
  end

  def test_parse_message_undeleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"message.undeleted"}')
    assert_equal 'StreamChat::MessageUndeletedEvent', event.class.name
  end

  def test_parse_message_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"message.updated"}')
    assert_equal 'StreamChat::MessageUpdatedEvent', event.class.name
  end

  def test_parse_moderation_custom_action
    event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation.custom_action"}')
    assert_equal 'StreamChat::ModerationCustomActionEvent', event.class.name
  end

  def test_parse_moderation_flagged
    event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation.flagged"}')
    assert_equal 'StreamChat::ModerationFlaggedEvent', event.class.name
  end

  def test_parse_moderation_mark_reviewed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation.mark_reviewed"}')
    assert_equal 'StreamChat::ModerationMarkReviewedEvent', event.class.name
  end

  def test_parse_moderation_check_completed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation_check.completed"}')
    assert_equal 'StreamChat::ModerationCheckCompletedEvent', event.class.name
  end

  def test_parse_moderation_rule_triggered
    event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation_rule.triggered"}')
    assert_equal 'StreamChat::ModerationRulesTriggeredEvent', event.class.name
  end

  def test_parse_notification_mark_unread
    event = StreamChat::Webhook.parse_webhook_event('{"type":"notification.mark_unread"}')
    assert_equal 'StreamChat::NotificationMarkUnreadEvent', event.class.name
  end

  def test_parse_notification_reminder_due
    event = StreamChat::Webhook.parse_webhook_event('{"type":"notification.reminder_due"}')
    assert_equal 'StreamChat::ReminderNotificationEvent', event.class.name
  end

  def test_parse_notification_thread_message_new
    event = StreamChat::Webhook.parse_webhook_event('{"type":"notification.thread_message_new"}')
    assert_equal 'StreamChat::NotificationThreadMessageNewEvent', event.class.name
  end

  def test_parse_reaction_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"reaction.deleted"}')
    assert_equal 'StreamChat::ReactionDeletedEvent', event.class.name
  end

  def test_parse_reaction_new
    event = StreamChat::Webhook.parse_webhook_event('{"type":"reaction.new"}')
    assert_equal 'StreamChat::ReactionNewEvent', event.class.name
  end

  def test_parse_reaction_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"reaction.updated"}')
    assert_equal 'StreamChat::ReactionUpdatedEvent', event.class.name
  end

  def test_parse_reminder_created
    event = StreamChat::Webhook.parse_webhook_event('{"type":"reminder.created"}')
    assert_equal 'StreamChat::ReminderCreatedEvent', event.class.name
  end

  def test_parse_reminder_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"reminder.deleted"}')
    assert_equal 'StreamChat::ReminderDeletedEvent', event.class.name
  end

  def test_parse_reminder_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"reminder.updated"}')
    assert_equal 'StreamChat::ReminderUpdatedEvent', event.class.name
  end

  def test_parse_review_queue_item_new
    event = StreamChat::Webhook.parse_webhook_event('{"type":"review_queue_item.new"}')
    assert_equal 'StreamChat::ReviewQueueItemNewEvent', event.class.name
  end

  def test_parse_review_queue_item_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"review_queue_item.updated"}')
    assert_equal 'StreamChat::ReviewQueueItemUpdatedEvent', event.class.name
  end

  def test_parse_thread_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"thread.updated"}')
    assert_equal 'StreamChat::ThreadUpdatedEvent', event.class.name
  end

  def test_parse_user_banned
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.banned"}')
    assert_equal 'StreamChat::UserBannedEvent', event.class.name
  end

  def test_parse_user_deactivated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.deactivated"}')
    assert_equal 'StreamChat::UserDeactivatedEvent', event.class.name
  end

  def test_parse_user_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.deleted"}')
    assert_equal 'StreamChat::UserDeletedEvent', event.class.name
  end

  def test_parse_user_flagged
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.flagged"}')
    assert_equal 'StreamChat::UserFlaggedEvent', event.class.name
  end

  def test_parse_user_messages_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.messages.deleted"}')
    assert_equal 'StreamChat::UserMessagesDeletedEvent', event.class.name
  end

  def test_parse_user_muted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.muted"}')
    assert_equal 'StreamChat::UserMutedEvent', event.class.name
  end

  def test_parse_user_reactivated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.reactivated"}')
    assert_equal 'StreamChat::UserReactivatedEvent', event.class.name
  end

  def test_parse_user_unbanned
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.unbanned"}')
    assert_equal 'StreamChat::UserUnbannedEvent', event.class.name
  end

  def test_parse_user_unmuted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.unmuted"}')
    assert_equal 'StreamChat::UserUnmutedEvent', event.class.name
  end

  def test_parse_user_unread_message_reminder
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.unread_message_reminder"}')
    assert_equal 'StreamChat::UserUnreadReminderEvent', event.class.name
  end

  def test_parse_user_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user.updated"}')
    assert_equal 'StreamChat::UserUpdatedEvent', event.class.name
  end

  def test_parse_user_group_created
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.created"}')
    assert_equal 'StreamChat::UserGroupCreatedEvent', event.class.name
  end

  def test_parse_user_group_deleted
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.deleted"}')
    assert_equal 'StreamChat::UserGroupDeletedEvent', event.class.name
  end

  def test_parse_user_group_member_added
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.member_added"}')
    assert_equal 'StreamChat::UserGroupMemberAddedEvent', event.class.name
  end

  def test_parse_user_group_member_removed
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.member_removed"}')
    assert_equal 'StreamChat::UserGroupMemberRemovedEvent', event.class.name
  end

  def test_parse_user_group_updated
    event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.updated"}')
    assert_equal 'StreamChat::UserGroupUpdatedEvent', event.class.name
  end

  def test_parse_webhook_event_unknown_type
    assert_raises(ArgumentError) do
      StreamChat::Webhook.parse_webhook_event('{"type":"unknown.event"}')
    end
  end

  def test_parse_webhook_event_missing_type
    assert_raises(ArgumentError) do
      StreamChat::Webhook.parse_webhook_event('{"foo":"bar"}')
    end
  end

  def test_parse_webhook_event_invalid_json
    assert_raises(ArgumentError) do
      StreamChat::Webhook.parse_webhook_event('not json')
    end
  end

  # ---------------------------------------------------------------------------
  # Spec §6 helpers + composites: parse_event, gunzip_payload, decode_sqs_payload,
  # decode_sns_payload, verify_and_parse_webhook, parse_sqs, parse_sns.
  # ---------------------------------------------------------------------------

  def test_stream_webhook_canonical_alias_resolves
    # Spec §7: Stream::Webhook is the canonical name; should alias StreamChat::Webhook.
    assert_equal StreamChat::Webhook, Stream::Webhook
  end

  def test_parse_event_returns_unknown_event_for_unknown_discriminator
    body = '{"type":"totally.made.up","created_at":"2026-05-08T00:00:00Z"}'
    event = StreamChat::Webhook.parse_event(body)
    assert_kind_of StreamChat::Webhook::UnknownEvent, event
    assert_equal 'totally.made.up', event.type
    refute_nil event.created_at
    assert_equal 'totally.made.up', event.raw['type']
  end

  def test_parse_event_empty_body
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_event('')
    end
  end

  def test_parse_event_invalid_json
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_event('not json')
    end
  end

  def test_parse_event_non_object_json
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_event('[1,2,3]')
    end
  end

  def test_parse_event_missing_type
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_event('{"foo":"bar"}')
    end
  end

  def test_gunzip_payload_passes_through_plain_body
    plain = '{"type":"message.new"}'
    assert_equal plain.b, StreamChat::Webhook.gunzip_payload(plain)
  end

  def test_gunzip_payload_decompresses_gzip_body
    plain = '{"type":"message.new"}'
    gz = Zlib.gzip(plain)
    assert_equal plain, StreamChat::Webhook.gunzip_payload(gz)
  end

  def test_gunzip_payload_raises_on_corrupt_gzip
    corrupt = "\x1F\x8Bnot-actually-a-gzip-stream".b
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.gunzip_payload(corrupt)
    end
  end

  def test_decode_sqs_payload_decodes_plain_base64
    plain = '{"type":"message.new"}'
    encoded = Base64.strict_encode64(plain)
    assert_equal plain.b, StreamChat::Webhook.decode_sqs_payload(encoded)
  end

  def test_decode_sqs_payload_decodes_base64_gzip_body
    plain = '{"type":"message.new"}'
    gz = Zlib.gzip(plain)
    encoded = Base64.strict_encode64(gz)
    assert_equal plain, StreamChat::Webhook.decode_sqs_payload(encoded)
  end

  def test_decode_sqs_payload_raises_on_invalid_base64
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.decode_sqs_payload('!!!not base64!!!')
    end
  end

  def test_decode_sns_payload_extracts_and_decodes_message
    plain = '{"type":"message.new"}'
    envelope = JSON.generate(
      'Type' => 'Notification',
      'Message' => Base64.strict_encode64(plain),
      'MessageId' => 'abc-123',
      'Timestamp' => '2026-05-08T00:00:00Z',
      'TopicArn' => 'arn:aws:sns:us-east-1:123:test'
    )
    assert_equal plain.b, StreamChat::Webhook.decode_sns_payload(envelope)
  end

  def test_decode_sns_payload_raises_on_invalid_envelope
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.decode_sns_payload('not json')
    end
  end

  def test_decode_sns_payload_raises_on_missing_message_field
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.decode_sns_payload('{"Type":"Notification"}')
    end
  end

  def test_verify_and_parse_webhook_happy_path
    body = '{"type":"message.new"}'
    sig = compute_signature(body, SECRET)
    refute_nil StreamChat::Webhook.verify_and_parse_webhook(body, sig, SECRET)
  end

  def test_verify_and_parse_webhook_gzip_body
    body = '{"type":"message.new"}'
    sig = compute_signature(body, SECRET)
    gz = Zlib.gzip(body)
    refute_nil StreamChat::Webhook.verify_and_parse_webhook(gz, sig, SECRET)
  end

  def test_verify_and_parse_webhook_raises_on_tampered_body
    body = '{"type":"message.new"}'
    sig = compute_signature(body, SECRET)
    assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.verify_and_parse_webhook('{"type":"message.deleted"}', sig, SECRET)
    end
  end

  def test_parse_sqs_happy_path
    plain = '{"type":"message.new"}'
    refute_nil StreamChat::Webhook.parse_sqs(Base64.strict_encode64(plain))
  end

  def test_parse_sns_happy_path
    plain = '{"type":"message.new"}'
    envelope = JSON.generate(
      'Type' => 'Notification',
      'Message' => Base64.strict_encode64(plain)
    )
    refute_nil StreamChat::Webhook.parse_sns(envelope)
  end
end

# ---------------------------------------------------------------------------
# Fixture-driven conformance tests. Fixtures live at test/fixtures/webhooks/
# (one subdirectory per case for happy path; _invalid/ for negative cases).
# ---------------------------------------------------------------------------
class WebhookConformanceTest < Minitest::Test
  CANONICAL_TEST_SECRET = 'test_secret_do_not_use_in_production'
  FIXTURE_ROOT = File.expand_path('fixtures/webhooks', __dir__).freeze

  def fixtures_present?
    File.directory?(FIXTURE_ROOT)
  end

  def each_happy_dir
    return unless fixtures_present?

    Dir.children(FIXTURE_ROOT).sort.each do |name|
      next if name == '_invalid'

      dir = File.join(FIXTURE_ROOT, name)
      next unless File.directory?(dir)

      yield name, dir
    end
  end

  def test_happy_fixtures
    skip 'webhook conformance fixtures not present' unless fixtures_present?

    each_happy_dir do |name, dir|
      body = File.binread(File.join(dir, 'body.json'))
      body_gz = File.binread(File.join(dir, 'body.gz'))
      sqs_compressed = File.read(File.join(dir, 'sqs_body.txt')).strip
      sqs_raw = File.read(File.join(dir, 'sqs_body_uncompressed.txt')).strip
      sns = File.read(File.join(dir, 'sns_notification.txt')).strip
      sig = File.read(File.join(dir, 'signature.txt')).strip

      assert StreamChat::Webhook.verify_signature(body, sig, CANONICAL_TEST_SECRET),
             "verify_signature failed for #{name}"
      refute_nil StreamChat::Webhook.parse_event(body),
                 "parse_event nil for #{name}"
      refute_nil StreamChat::Webhook.verify_and_parse_webhook(body, sig, CANONICAL_TEST_SECRET),
                 "verify_and_parse_webhook (identity) failed for #{name}"
      refute_nil StreamChat::Webhook.verify_and_parse_webhook(body_gz, sig, CANONICAL_TEST_SECRET),
                 "verify_and_parse_webhook (gzip) failed for #{name}"
      refute_nil StreamChat::Webhook.parse_sqs(sqs_compressed),
                 "parse_sqs (compressed) failed for #{name}"
      refute_nil StreamChat::Webhook.parse_sqs(sqs_raw),
                 "parse_sqs (uncompressed) failed for #{name}"
      refute_nil StreamChat::Webhook.parse_sns(sns),
                 "parse_sns failed for #{name}"
    end
  end

  def neg_dir(name)
    File.join(FIXTURE_ROOT, '_invalid', name)
  end

  def test_tampered_body
    skip 'fixtures not present' unless fixtures_present?

    body = File.binread(File.join(neg_dir('tampered_body'), 'body.json'))
    sig = File.read(File.join(neg_dir('tampered_body'), 'signature.txt')).strip
    err = assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.verify_and_parse_webhook(body, sig, CANONICAL_TEST_SECRET)
    end
    assert_includes err.message, 'signature mismatch'
  end

  def test_unknown_type_returns_unknown_event
    skip 'fixtures not present' unless fixtures_present?

    body = File.binread(File.join(neg_dir('unknown_type'), 'body.json'))
    result = StreamChat::Webhook.parse_event(body)
    assert_kind_of StreamChat::Webhook::UnknownEvent, result
    assert_equal 'totally.made.up', result.type
  end

  def test_missing_type
    skip 'fixtures not present' unless fixtures_present?

    body = File.binread(File.join(neg_dir('missing_type'), 'body.json'))
    err = assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_event(body)
    end
    assert_includes err.message, "missing 'type'"
  end

  def test_malformed_json
    skip 'fixtures not present' unless fixtures_present?

    body = File.binread(File.join(neg_dir('malformed_json'), 'body.json'))
    err = assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_event(body)
    end
    assert_includes err.message, 'failed to parse webhook payload'
  end

  def test_empty_body
    skip 'fixtures not present' unless fixtures_present?

    body = File.binread(File.join(neg_dir('empty_body'), 'body.json'))
    err = assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_event(body)
    end
    assert_includes err.message, 'must not be empty'
  end

  def test_bad_compression
    skip 'fixtures not present' unless fixtures_present?

    body = File.binread(File.join(neg_dir('bad_compression'), 'body.gz'))
    err = assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.gunzip_payload(body)
    end
    assert_includes err.message, 'gzip decompression failed'
  end

  def test_bad_base64
    skip 'fixtures not present' unless fixtures_present?

    msg = File.read(File.join(neg_dir('bad_base64'), 'sqs_body.txt')).strip
    err = assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_sqs(msg)
    end
    assert_includes err.message, 'base64'
  end

  def test_bad_sns_envelope
    skip 'fixtures not present' unless fixtures_present?

    notif = File.read(File.join(neg_dir('bad_sns_envelope'), 'sns_notification.txt')).strip
    err = assert_raises(StreamChat::Webhook::InvalidWebhookError) do
      StreamChat::Webhook.parse_sns(notif)
    end
    assert_includes err.message, 'SNS envelope'
  end
end
