# frozen_string_literal: true

# Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

require 'spec_helper'

require 'base64'
require 'json'
require 'openssl'
require 'zlib'

require_relative '../lib/getstream_ruby/generated/webhook'

# Top-level constants, pulled out of the RSpec.describe blocks below to avoid
# Lint/ConstantDefinitionInBlock. WEBHOOK_FIXTURE_ROOT is evaluated at file-load
# time so the `Dir.children` iteration below can build the per-fixture contexts.
WEBHOOK_TEST_SECRET = 'test-webhook-secret'
WEBHOOK_TEST_BODY = '{"type":"test.event"}'
WEBHOOK_CONFORMANCE_SECRET = 'test_secret_do_not_use_in_production'
WEBHOOK_FIXTURE_ROOT = File.expand_path('../test/fixtures/webhooks', __dir__)

def compute_signature(body, secret)
  OpenSSL::HMAC.hexdigest('SHA256', secret, body)
end

RSpec.describe 'Webhook' do

  describe 'verify_signature' do

    it 'accepts a valid signature' do

      signature = compute_signature(WEBHOOK_TEST_BODY, WEBHOOK_TEST_SECRET)
      expect(StreamChat::Webhook.verify_signature(WEBHOOK_TEST_BODY, signature, WEBHOOK_TEST_SECRET)).to be true

    end

    it 'rejects a wrong signature' do

      result = StreamChat::Webhook.verify_signature(WEBHOOK_TEST_BODY, 'invalidsignature', WEBHOOK_TEST_SECRET)
      expect(result).to be false

    end

    it 'rejects a tampered body' do

      signature = compute_signature(WEBHOOK_TEST_BODY, WEBHOOK_TEST_SECRET)
      expect(StreamChat::Webhook.verify_signature('{"type":"tampered"}', signature, WEBHOOK_TEST_SECRET)).to be false

    end

    it 'rejects a wrong secret' do

      signature = compute_signature(WEBHOOK_TEST_BODY, WEBHOOK_TEST_SECRET)
      expect(StreamChat::Webhook.verify_signature(WEBHOOK_TEST_BODY, signature, 'wrong-secret')).to be false

    end

    it 'rejects an empty signature' do

      expect(StreamChat::Webhook.verify_signature(WEBHOOK_TEST_BODY, '', WEBHOOK_TEST_SECRET)).to be false

    end

  end

  describe 'get_event_type' do

    it 'reads the type from a string payload' do

      expect(StreamChat::Webhook.get_event_type('{"type":"message.new"}')).to eq('message.new')

    end

    it 'reads the type from a hash payload' do

      expect(StreamChat::Webhook.get_event_type({ 'type' => 'message.new' })).to eq('message.new')

    end

    it 'returns nil when the type field is missing' do

      expect(StreamChat::Webhook.get_event_type('{"foo":"bar"}')).to be_nil

    end

    it 'returns nil for an empty object' do

      expect(StreamChat::Webhook.get_event_type('{}')).to be_nil

    end

  end

  describe 'parse_webhook_event' do

    it 'parses *' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"*"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CustomEvent')

    end

    it 'parses appeal.accepted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"appeal.accepted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AppealAcceptedEvent')

    end

    it 'parses appeal.created' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"appeal.created"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AppealCreatedEvent')

    end

    it 'parses appeal.rejected' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"appeal.rejected"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AppealRejectedEvent')

    end

    it 'parses call.accepted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.accepted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallAcceptedEvent')

    end

    it 'parses call.blocked_user' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.blocked_user"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::BlockedUserEvent')

    end

    it 'parses call.closed_caption' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.closed_caption"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ClosedCaptionEvent')

    end

    it 'parses call.closed_captions_failed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.closed_captions_failed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallClosedCaptionsFailedEvent')

    end

    it 'parses call.closed_captions_started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.closed_captions_started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallClosedCaptionsStartedEvent')

    end

    it 'parses call.closed_captions_stopped' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.closed_captions_stopped"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallClosedCaptionsStoppedEvent')

    end

    it 'parses call.created' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.created"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallCreatedEvent')

    end

    it 'parses call.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallDeletedEvent')

    end

    it 'parses call.dtmf' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.dtmf"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallDTMFEvent')

    end

    it 'parses call.ended' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.ended"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallEndedEvent')

    end

    it 'parses call.frame_recording_failed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.frame_recording_failed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallFrameRecordingFailedEvent')

    end

    it 'parses call.frame_recording_ready' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.frame_recording_ready"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallFrameRecordingFrameReadyEvent')

    end

    it 'parses call.frame_recording_started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.frame_recording_started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallFrameRecordingStartedEvent')

    end

    it 'parses call.frame_recording_stopped' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.frame_recording_stopped"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallFrameRecordingStoppedEvent')

    end

    it 'parses call.hls_broadcasting_failed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.hls_broadcasting_failed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallHLSBroadcastingFailedEvent')

    end

    it 'parses call.hls_broadcasting_started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.hls_broadcasting_started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallHLSBroadcastingStartedEvent')

    end

    it 'parses call.hls_broadcasting_stopped' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.hls_broadcasting_stopped"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallHLSBroadcastingStoppedEvent')

    end

    it 'parses call.kicked_user' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.kicked_user"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::KickedUserEvent')

    end

    it 'parses call.live_started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.live_started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallLiveStartedEvent')

    end

    it 'parses call.member_added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.member_added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallMemberAddedEvent')

    end

    it 'parses call.member_removed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.member_removed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallMemberRemovedEvent')

    end

    it 'parses call.member_updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.member_updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallMemberUpdatedEvent')

    end

    it 'parses call.member_updated_permission' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.member_updated_permission"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallMemberUpdatedPermissionEvent')

    end

    it 'parses call.missed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.missed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallMissedEvent')

    end

    it 'parses call.moderation_blur' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.moderation_blur"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallModerationBlurEvent')

    end

    it 'parses call.moderation_warning' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.moderation_warning"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallModerationWarningEvent')

    end

    it 'parses call.notification' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.notification"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallNotificationEvent')

    end

    it 'parses call.permission_request' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.permission_request"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::PermissionRequestEvent')

    end

    it 'parses call.permissions_updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.permissions_updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UpdatedCallPermissionsEvent')

    end

    it 'parses call.reaction_new' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.reaction_new"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallReactionEvent')

    end

    it 'parses call.recording_failed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.recording_failed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRecordingFailedEvent')

    end

    it 'parses call.recording_ready' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.recording_ready"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRecordingReadyEvent')

    end

    it 'parses call.recording_started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.recording_started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRecordingStartedEvent')

    end

    it 'parses call.recording_stopped' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.recording_stopped"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRecordingStoppedEvent')

    end

    it 'parses call.rejected' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.rejected"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRejectedEvent')

    end

    it 'parses call.ring' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.ring"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRingEvent')

    end

    it 'parses call.rtmp_broadcast_failed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.rtmp_broadcast_failed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRtmpBroadcastFailedEvent')

    end

    it 'parses call.rtmp_broadcast_started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.rtmp_broadcast_started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRtmpBroadcastStartedEvent')

    end

    it 'parses call.rtmp_broadcast_stopped' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.rtmp_broadcast_stopped"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallRtmpBroadcastStoppedEvent')

    end

    it 'parses call.session_ended' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_ended"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallSessionEndedEvent')

    end

    it 'parses call.session_participant_count_updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_participant_count_updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallSessionParticipantCountsUpdatedEvent')

    end

    it 'parses call.session_participant_joined' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_participant_joined"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallSessionParticipantJoinedEvent')

    end

    it 'parses call.session_participant_left' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_participant_left"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallSessionParticipantLeftEvent')

    end

    it 'parses call.session_started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.session_started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallSessionStartedEvent')

    end

    it 'parses call.stats_report_ready' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.stats_report_ready"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallStatsReportReadyEvent')

    end

    it 'parses call.transcription_failed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.transcription_failed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallTranscriptionFailedEvent')

    end

    it 'parses call.transcription_ready' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.transcription_ready"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallTranscriptionReadyEvent')

    end

    it 'parses call.transcription_started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.transcription_started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallTranscriptionStartedEvent')

    end

    it 'parses call.transcription_stopped' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.transcription_stopped"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallTranscriptionStoppedEvent')

    end

    it 'parses call.unblocked_user' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.unblocked_user"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UnblockedUserEvent')

    end

    it 'parses call.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallUpdatedEvent')

    end

    it 'parses call.user_feedback_submitted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.user_feedback_submitted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallUserFeedbackSubmittedEvent')

    end

    it 'parses call.user_muted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"call.user_muted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CallUserMutedEvent')

    end

    it 'parses campaign.completed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"campaign.completed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CampaignCompletedEvent')

    end

    it 'parses campaign.started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"campaign.started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CampaignStartedEvent')

    end

    it 'parses channel.created' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.created"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelCreatedEvent')

    end

    it 'parses channel.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelDeletedEvent')

    end

    it 'parses channel.frozen' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.frozen"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelFrozenEvent')

    end

    it 'parses channel.hidden' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.hidden"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelHiddenEvent')

    end

    it 'parses channel.max_streak_changed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.max_streak_changed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MaxStreakChangedEvent')

    end

    it 'parses channel.muted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.muted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelMutedEvent')

    end

    it 'parses channel.truncated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.truncated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelTruncatedEvent')

    end

    it 'parses channel.unfrozen' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.unfrozen"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelUnFrozenEvent')

    end

    it 'parses channel.unmuted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.unmuted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelUnmutedEvent')

    end

    it 'parses channel.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelUpdatedEvent')

    end

    it 'parses channel.visible' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel.visible"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelVisibleEvent')

    end

    it 'parses channel_batch_update.completed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel_batch_update.completed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelBatchCompletedEvent')

    end

    it 'parses channel_batch_update.started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"channel_batch_update.started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ChannelBatchStartedEvent')

    end

    it 'parses custom' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"custom"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CustomVideoEvent')

    end

    it 'parses export.bulk_image_moderation.error' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"export.bulk_image_moderation.error"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AsyncExportErrorEvent')

    end

    it 'parses export.bulk_image_moderation.success' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"export.bulk_image_moderation.success"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AsyncBulkImageModerationEvent')

    end

    it 'parses export.channels.error' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"export.channels.error"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AsyncExportErrorEvent')

    end

    it 'parses export.channels.success' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"export.channels.success"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AsyncExportChannelsEvent')

    end

    it 'parses export.moderation_logs.error' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"export.moderation_logs.error"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AsyncExportErrorEvent')

    end

    it 'parses export.moderation_logs.success' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"export.moderation_logs.success"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AsyncExportModerationLogsEvent')

    end

    it 'parses export.users.error' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"export.users.error"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AsyncExportErrorEvent')

    end

    it 'parses export.users.success' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"export.users.success"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::AsyncExportUsersEvent')

    end

    it 'parses feeds.activity.added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityAddedEvent')

    end

    it 'parses feeds.activity.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityDeletedEvent')

    end

    it 'parses feeds.activity.feedback' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.feedback"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityFeedbackEvent')

    end

    it 'parses feeds.activity.marked' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.marked"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityMarkEvent')

    end

    it 'parses feeds.activity.pinned' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.pinned"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityPinnedEvent')

    end

    it 'parses feeds.activity.reaction.added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.reaction.added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityReactionAddedEvent')

    end

    it 'parses feeds.activity.reaction.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.reaction.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityReactionDeletedEvent')

    end

    it 'parses feeds.activity.reaction.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.reaction.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityReactionUpdatedEvent')

    end

    it 'parses feeds.activity.removed_from_feed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.removed_from_feed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityRemovedFromFeedEvent')

    end

    it 'parses feeds.activity.restored' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.restored"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityRestoredEvent')

    end

    it 'parses feeds.activity.unpinned' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.unpinned"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityUnpinnedEvent')

    end

    it 'parses feeds.activity.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.activity.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ActivityUpdatedEvent')

    end

    it 'parses feeds.bookmark.added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark.added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::BookmarkAddedEvent')

    end

    it 'parses feeds.bookmark.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::BookmarkDeletedEvent')

    end

    it 'parses feeds.bookmark.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::BookmarkUpdatedEvent')

    end

    it 'parses feeds.bookmark_folder.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark_folder.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::BookmarkFolderDeletedEvent')

    end

    it 'parses feeds.bookmark_folder.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.bookmark_folder.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::BookmarkFolderUpdatedEvent')

    end

    it 'parses feeds.comment.added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CommentAddedEvent')

    end

    it 'parses feeds.comment.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CommentDeletedEvent')

    end

    it 'parses feeds.comment.reaction.added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.reaction.added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CommentReactionAddedEvent')

    end

    it 'parses feeds.comment.reaction.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.reaction.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CommentReactionDeletedEvent')

    end

    it 'parses feeds.comment.reaction.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.reaction.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CommentReactionUpdatedEvent')

    end

    it 'parses feeds.comment.restored' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.restored"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CommentRestoredEvent')

    end

    it 'parses feeds.comment.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.comment.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::CommentUpdatedEvent')

    end

    it 'parses feeds.feed.created' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed.created"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedCreatedEvent')

    end

    it 'parses feeds.feed.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedDeletedEvent')

    end

    it 'parses feeds.feed.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedUpdatedEvent')

    end

    it 'parses feeds.feed_group.changed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_group.changed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedGroupChangedEvent')

    end

    it 'parses feeds.feed_group.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_group.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedGroupDeletedEvent')

    end

    it 'parses feeds.feed_group.restored' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_group.restored"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedGroupRestoredEvent')

    end

    it 'parses feeds.feed_member.added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_member.added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedMemberAddedEvent')

    end

    it 'parses feeds.feed_member.removed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_member.removed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedMemberRemovedEvent')

    end

    it 'parses feeds.feed_member.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.feed_member.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FeedMemberUpdatedEvent')

    end

    it 'parses feeds.follow.created' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.follow.created"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FollowCreatedEvent')

    end

    it 'parses feeds.follow.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.follow.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FollowDeletedEvent')

    end

    it 'parses feeds.follow.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.follow.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FollowUpdatedEvent')

    end

    it 'parses feeds.notification_feed.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.notification_feed.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::NotificationFeedUpdatedEvent')

    end

    it 'parses feeds.stories_feed.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"feeds.stories_feed.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::StoriesFeedUpdatedEvent')

    end

    it 'parses flag.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"flag.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::FlagUpdatedEvent')

    end

    it 'parses ingress.error' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"ingress.error"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::IngressErrorEvent')

    end

    it 'parses ingress.started' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"ingress.started"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::IngressStartedEvent')

    end

    it 'parses ingress.stopped' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"ingress.stopped"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::IngressStoppedEvent')

    end

    it 'parses member.added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"member.added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MemberAddedEvent')

    end

    it 'parses member.removed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"member.removed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MemberRemovedEvent')

    end

    it 'parses member.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"member.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MemberUpdatedEvent')

    end

    it 'parses message.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"message.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MessageDeletedEvent')

    end

    it 'parses message.flagged' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"message.flagged"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MessageFlaggedEvent')

    end

    it 'parses message.new' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"message.new"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MessageNewEvent')

    end

    it 'parses message.pending' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"message.pending"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::PendingMessageEvent')

    end

    it 'parses message.read' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"message.read"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MessageReadEvent')

    end

    it 'parses message.unblocked' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"message.unblocked"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MessageUnblockedEvent')

    end

    it 'parses message.undeleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"message.undeleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MessageUndeletedEvent')

    end

    it 'parses message.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"message.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::MessageUpdatedEvent')

    end

    it 'parses moderation.custom_action' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation.custom_action"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ModerationCustomActionEvent')

    end

    it 'parses moderation.flagged' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation.flagged"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ModerationFlaggedEvent')

    end

    it 'parses moderation.image_analysis.complete' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation.image_analysis.complete"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ModerationImageAnalysisCompleteEvent')

    end

    it 'parses moderation.mark_reviewed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation.mark_reviewed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ModerationMarkReviewedEvent')

    end

    it 'parses moderation.text_analysis.complete' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation.text_analysis.complete"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ModerationTextAnalysisCompleteEvent')

    end

    it 'parses moderation_check.completed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation_check.completed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ModerationCheckCompletedEvent')

    end

    it 'parses moderation_rule.triggered' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"moderation_rule.triggered"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ModerationRulesTriggeredEvent')

    end

    it 'parses notification.mark_unread' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"notification.mark_unread"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::NotificationMarkUnreadEvent')

    end

    it 'parses notification.reminder_due' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"notification.reminder_due"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReminderNotificationEvent')

    end

    it 'parses notification.thread_message_new' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"notification.thread_message_new"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::NotificationThreadMessageNewEvent')

    end

    it 'parses reaction.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"reaction.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReactionDeletedEvent')

    end

    it 'parses reaction.new' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"reaction.new"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReactionNewEvent')

    end

    it 'parses reaction.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"reaction.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReactionUpdatedEvent')

    end

    it 'parses reminder.created' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"reminder.created"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReminderCreatedEvent')

    end

    it 'parses reminder.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"reminder.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReminderDeletedEvent')

    end

    it 'parses reminder.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"reminder.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReminderUpdatedEvent')

    end

    it 'parses review_queue_item.new' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"review_queue_item.new"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReviewQueueItemNewEvent')

    end

    it 'parses review_queue_item.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"review_queue_item.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ReviewQueueItemUpdatedEvent')

    end

    it 'parses thread.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"thread.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::ThreadUpdatedEvent')

    end

    it 'parses user.banned' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.banned"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserBannedEvent')

    end

    it 'parses user.deactivated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.deactivated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserDeactivatedEvent')

    end

    it 'parses user.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserDeletedEvent')

    end

    it 'parses user.flagged' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.flagged"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserFlaggedEvent')

    end

    it 'parses user.messages.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.messages.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserMessagesDeletedEvent')

    end

    it 'parses user.muted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.muted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserMutedEvent')

    end

    it 'parses user.reactivated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.reactivated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserReactivatedEvent')

    end

    it 'parses user.unbanned' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.unbanned"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserUnbannedEvent')

    end

    it 'parses user.unmuted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.unmuted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserUnmutedEvent')

    end

    it 'parses user.unread_message_reminder' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.unread_message_reminder"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserUnreadReminderEvent')

    end

    it 'parses user.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserUpdatedEvent')

    end

    it 'parses user_group.created' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.created"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserGroupCreatedEvent')

    end

    it 'parses user_group.deleted' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.deleted"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserGroupDeletedEvent')

    end

    it 'parses user_group.member_added' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.member_added"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserGroupMemberAddedEvent')

    end

    it 'parses user_group.member_removed' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.member_removed"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserGroupMemberRemovedEvent')

    end

    it 'parses user_group.updated' do

      event = StreamChat::Webhook.parse_webhook_event('{"type":"user_group.updated"}')
      expect(event.class.name).to eq('GetStream::Generated::Models::UserGroupUpdatedEvent')

    end

    it 'raises on unknown event type' do

      expect { StreamChat::Webhook.parse_webhook_event('{"type":"unknown.event"}') }.to raise_error(ArgumentError)

    end

    it 'raises when type field is missing' do

      expect { StreamChat::Webhook.parse_webhook_event('{"foo":"bar"}') }.to raise_error(ArgumentError)

    end

    it 'raises on invalid JSON' do

      expect { StreamChat::Webhook.parse_webhook_event('not json') }.to raise_error(ArgumentError)

    end

  end

  # ---------------------------------------------------------------------------
  # Spec §6 helpers + composites: parse_event, gunzip_payload, decode_sqs_payload,
  # decode_sns_payload, verify_and_parse_webhook, parse_sqs, parse_sns.
  # ---------------------------------------------------------------------------

  describe 'canonical alias' do

    it 'resolves Stream::Webhook to StreamChat::Webhook' do

      expect(Stream::Webhook).to eq(StreamChat::Webhook)

    end

  end

  describe 'parse_event' do

    it 'returns an UnknownEvent for unknown discriminator' do

      body = '{"type":"totally.made.up","created_at":"2026-05-08T00:00:00Z"}'
      event = StreamChat::Webhook.parse_event(body)
      expect(event).to be_a(StreamChat::Webhook::UnknownEvent)
      expect(event.type).to eq('totally.made.up')
      expect(event.created_at).not_to be_nil
      expect(event.raw['type']).to eq('totally.made.up')

    end

    it 'raises on empty body' do

      expect { StreamChat::Webhook.parse_event('') }.to raise_error(StreamChat::Webhook::InvalidWebhookError)

    end

    it 'raises on invalid JSON' do

      expect { StreamChat::Webhook.parse_event('not json') }.to raise_error(StreamChat::Webhook::InvalidWebhookError)

    end

    it 'raises on non-object JSON' do

      expect { StreamChat::Webhook.parse_event('[1,2,3]') }.to raise_error(StreamChat::Webhook::InvalidWebhookError)

    end

    it 'raises when type field is missing' do

      err_class = StreamChat::Webhook::InvalidWebhookError
      expect { StreamChat::Webhook.parse_event('{"foo":"bar"}') }.to raise_error(err_class)

    end

  end

  describe 'gunzip_payload' do

    it 'passes through a plain body' do

      plain = '{"type":"message.new"}'
      expect(StreamChat::Webhook.gunzip_payload(plain)).to eq(plain.b)

    end

    it 'decompresses a gzip body' do

      plain = '{"type":"message.new"}'
      gz = Zlib.gzip(plain)
      expect(StreamChat::Webhook.gunzip_payload(gz)).to eq(plain)

    end

    it 'raises on a corrupt gzip stream' do

      corrupt = "\x1F\x8Bnot-actually-a-gzip-stream".b
      expect { StreamChat::Webhook.gunzip_payload(corrupt) }.to raise_error(StreamChat::Webhook::InvalidWebhookError)

    end

  end

  describe 'decode_sqs_payload' do

    it 'decodes plain base64' do

      plain = '{"type":"message.new"}'
      encoded = Base64.strict_encode64(plain)
      expect(StreamChat::Webhook.decode_sqs_payload(encoded)).to eq(plain.b)

    end

    it 'decodes base64-then-gzip payload' do

      plain = '{"type":"message.new"}'
      gz = Zlib.gzip(plain)
      encoded = Base64.strict_encode64(gz)
      expect(StreamChat::Webhook.decode_sqs_payload(encoded)).to eq(plain)

    end

    it 'passes through non-base64 raw JSON' do

      # Per chat#13392 wire format: SQS bodies are raw JSON when
      # hook_payload_compression is off. decode_sqs_payload must fall back to
      # raw bytes on non-base64 input rather than raise.
      plain = '{"type":"message.new"}'
      expect(StreamChat::Webhook.decode_sqs_payload(plain)).to eq(plain)

    end

  end

  describe 'decode_sns_payload' do

    it 'extracts and decodes the inner Message' do

      plain = '{"type":"message.new"}'
      envelope = JSON.generate(
        'Type' => 'Notification',
        'Message' => Base64.strict_encode64(plain),
        'MessageId' => 'abc-123',
        'Timestamp' => '2026-05-08T00:00:00Z',
        'TopicArn' => 'arn:aws:sns:us-east-1:123:test',
      )
      expect(StreamChat::Webhook.decode_sns_payload(envelope)).to eq(plain.b)

    end

    it 'treats non-envelope input as a raw Message string' do

      # decode_sns_payload accepts either a full SNS envelope or a
      # pre-extracted Message string. Non-envelope input flows through as bytes.
      expect(StreamChat::Webhook.decode_sns_payload('not json')).not_to be_nil

    end

    it 'treats envelope-shape without Message as raw' do

      # Envelope-shaped JSON without a string Message field is treated
      # as a pre-extracted Message string and flows through.
      expect(StreamChat::Webhook.decode_sns_payload('{"Type":"Notification"}')).not_to be_nil

    end

  end

  describe 'verify_and_parse_webhook' do

    it 'parses a valid happy-path body' do

      body = '{"type":"message.new"}'
      sig = compute_signature(body, WEBHOOK_TEST_SECRET)
      expect(StreamChat::Webhook.verify_and_parse_webhook(body, sig, WEBHOOK_TEST_SECRET)).not_to be_nil

    end

    it 'parses a valid gzip body' do

      body = '{"type":"message.new"}'
      sig = compute_signature(body, WEBHOOK_TEST_SECRET)
      gz = Zlib.gzip(body)
      expect(StreamChat::Webhook.verify_and_parse_webhook(gz, sig, WEBHOOK_TEST_SECRET)).not_to be_nil

    end

    it 'raises on tampered body' do

      body = '{"type":"message.new"}'
      sig = compute_signature(body, WEBHOOK_TEST_SECRET)
      tampered = '{"type":"message.deleted"}'
      err_class = StreamChat::Webhook::InvalidWebhookError
      # Single-arm rescue on the unified InvalidWebhookError; message identifies the mode.
      expect { StreamChat::Webhook.verify_and_parse_webhook(tampered, sig, WEBHOOK_TEST_SECRET) }
        .to raise_error(err_class, /#{err_class::SIGNATURE_MISMATCH}/)

    end

  end

  describe 'parse_sqs' do

    it 'parses a happy-path SQS body' do

      plain = '{"type":"message.new"}'
      expect(StreamChat::Webhook.parse_sqs(Base64.strict_encode64(plain))).not_to be_nil

    end

  end

  describe 'parse_sns' do

    it 'parses a happy-path SNS envelope' do

      plain = '{"type":"message.new"}'
      envelope = JSON.generate(
        'Type' => 'Notification',
        'Message' => Base64.strict_encode64(plain),
      )
      expect(StreamChat::Webhook.parse_sns(envelope)).not_to be_nil

    end

  end

end

# ---------------------------------------------------------------------------
# Fixture-driven conformance tests. Fixtures live at test/fixtures/webhooks/
# (one subdirectory per case for happy path; _invalid/ for negative cases).
# ---------------------------------------------------------------------------
RSpec.describe 'Webhook conformance', type: :integration do

  it 'has conformance fixtures present' do

    expect(File).to be_directory(WEBHOOK_FIXTURE_ROOT)

  end

  if File.directory?(WEBHOOK_FIXTURE_ROOT)

    Dir.children(WEBHOOK_FIXTURE_ROOT).sort.each do |name|

      next if name == '_invalid'

      dir = File.join(WEBHOOK_FIXTURE_ROOT, name)
      next unless File.directory?(dir)

      context "happy fixture #{name}" do

        it 'verifies signature, parses event, and round-trips all transports' do

          body = File.binread(File.join(dir, 'body.json'))
          body_gz = File.binread(File.join(dir, 'body.gz'))
          sqs_compressed = File.read(File.join(dir, 'sqs_body.txt')).strip
          sqs_raw = File.read(File.join(dir, 'sqs_body_uncompressed.txt')).strip
          sns = File.read(File.join(dir, 'sns_notification.txt')).strip
          sig = File.read(File.join(dir, 'signature.txt')).strip

          expect(StreamChat::Webhook.verify_signature(body, sig, WEBHOOK_CONFORMANCE_SECRET)).to be true
          expect(StreamChat::Webhook.parse_event(body)).not_to be_nil
          expect(StreamChat::Webhook.verify_and_parse_webhook(body, sig, WEBHOOK_CONFORMANCE_SECRET)).not_to be_nil
          expect(StreamChat::Webhook.verify_and_parse_webhook(body_gz, sig, WEBHOOK_CONFORMANCE_SECRET)).not_to be_nil
          expect(StreamChat::Webhook.parse_sqs(sqs_compressed)).not_to be_nil
          expect(StreamChat::Webhook.parse_sqs(sqs_raw)).not_to be_nil
          expect(StreamChat::Webhook.parse_sns(sns)).not_to be_nil

        end

      end

    end

  end

  context 'negative fixtures' do

    def neg_dir(name)
      File.join(WEBHOOK_FIXTURE_ROOT, '_invalid', name)
    end

    it 'rejects tampered body' do

      skip 'fixtures not present' unless File.directory?(WEBHOOK_FIXTURE_ROOT)

      body = File.binread(File.join(neg_dir('tampered_body'), 'body.json'))
      sig = File.read(File.join(neg_dir('tampered_body'), 'signature.txt')).strip
      err_class = StreamChat::Webhook::InvalidWebhookError
      expect { StreamChat::Webhook.verify_and_parse_webhook(body, sig, WEBHOOK_CONFORMANCE_SECRET) }
        .to raise_error(err_class, /#{err_class::SIGNATURE_MISMATCH}/)

    end

    it 'returns UnknownEvent for unknown type' do

      skip 'fixtures not present' unless File.directory?(WEBHOOK_FIXTURE_ROOT)

      body = File.binread(File.join(neg_dir('unknown_type'), 'body.json'))
      result = StreamChat::Webhook.parse_event(body)
      expect(result).to be_a(StreamChat::Webhook::UnknownEvent)
      expect(result.type).to eq('totally.made.up')

    end

    it 'raises when type field is missing' do

      skip 'fixtures not present' unless File.directory?(WEBHOOK_FIXTURE_ROOT)

      body = File.binread(File.join(neg_dir('missing_type'), 'body.json'))
      err_class = StreamChat::Webhook::InvalidWebhookError
      expect { StreamChat::Webhook.parse_event(body) }.to raise_error(err_class, /missing 'type'/)

    end

    it 'raises on malformed JSON' do

      skip 'fixtures not present' unless File.directory?(WEBHOOK_FIXTURE_ROOT)

      body = File.binread(File.join(neg_dir('malformed_json'), 'body.json'))
      err_class = StreamChat::Webhook::InvalidWebhookError
      expect { StreamChat::Webhook.parse_event(body) }.to raise_error(err_class, /failed to parse webhook payload/)

    end

    it 'raises on empty body' do

      skip 'fixtures not present' unless File.directory?(WEBHOOK_FIXTURE_ROOT)

      body = File.binread(File.join(neg_dir('empty_body'), 'body.json'))
      err_class = StreamChat::Webhook::InvalidWebhookError
      expect { StreamChat::Webhook.parse_event(body) }.to raise_error(err_class, /must not be empty/)

    end

    it 'raises on bad gzip compression' do

      skip 'fixtures not present' unless File.directory?(WEBHOOK_FIXTURE_ROOT)

      body = File.binread(File.join(neg_dir('bad_compression'), 'body.gz'))
      err_class = StreamChat::Webhook::InvalidWebhookError
      expect { StreamChat::Webhook.gunzip_payload(body) }.to raise_error(err_class, /gzip decompression failed/)

    end

    it 'raises on bad base64 (downstream parse failure)' do

      # Per CHA-3071 wire format: decode_sqs_payload falls back to raw bytes
      # when base64 decoding fails (uncompressed wire format). For input that
      # is neither valid base64 nor valid JSON nor gzip-prefixed, parse_sqs
      # still raises InvalidWebhookError, just down the chain at JSON parsing.
      skip 'fixtures not present' unless File.directory?(WEBHOOK_FIXTURE_ROOT)

      msg = File.read(File.join(neg_dir('bad_base64'), 'sqs_body.txt')).strip
      expect { StreamChat::Webhook.parse_sqs(msg) }.to raise_error(StreamChat::Webhook::InvalidWebhookError)

    end

    it 'raises on bad SNS envelope (downstream parse failure)' do

      # bad_sns_envelope (non-envelope JSON) is now treated as a pre-extracted
      # Message string and flows through the SQS path, surfacing as a downstream
      # parse failure rather than SNS-specific. Still InvalidWebhookError.
      skip 'fixtures not present' unless File.directory?(WEBHOOK_FIXTURE_ROOT)

      notif = File.read(File.join(neg_dir('bad_sns_envelope'), 'sns_notification.txt')).strip
      expect { StreamChat::Webhook.parse_sns(notif) }.to raise_error(StreamChat::Webhook::InvalidWebhookError)

    end

  end

end
